name: Build Godot Project

on:
  push:
    branches: ['dev']

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [mac, web]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Dev Build
        id: dev_build
        uses: manleydev/build-godot-action@f759ed7f8fcb5137cb70873ecf663aa8a1bd998b
        with:
          name: jam_dev_${{ matrix.platform }}
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
